title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Crypto Xtapo is dedicated to the latest crypto world news and recommendations, including stories from Coinbase, the most popular place to buy and sell digital ...
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://crypto.xtapo.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Crypto Xtapo # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a trader. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: xtapo # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: xtapo # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
