title: Mẹ Và Bé | Xtapo
description: > # this means to ignore newlines until "baseurl:"
  Những tư vấn dành riêng cho mẹ và bé yêu, Cập nhật liên tục những chia sẻ và câu chuyện về hành trình nuôi dạy trẻ của các mẹ và bé yêu...
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://mevabe.xtapo.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mẹ Và Bé - Xtapo # add your name
author-img: 130532.jpg # add your photo
about-author: Nơi chia sẻ và câu chuyện về hành trình nuôi dạy trẻ của các mẹ và bé yêu... # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: xtapo # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: xtapo # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
